name: Render a CV

on:
  push:
    branches:
      - main
  workflow_call:

permissions:
  contents: write

jobs:
  rendercv:
    name: RenderCV
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install RenderCV
        run: |
          pip install -r requirements.txt
      - name: RenderCV
        run: |
          # Find all files ending with 'CV.yaml' in the src dir
          cd src
          cv_files=$(find .  -maxdepth 1 -type f -name "*_CV.yaml")
          cd ..

          # If no files found, abort
          if [ -z "$cv_files" ]; then
              echo "No RenderCV file found!"
              exit 1
          fi

          # Render each found file
          for file in $cv_files; do
              echo "––––––––––––––––––"
              echo "Rendering $file..."
              rendercv render "./src/$file" -nohtml -nopng --output-folder-name "./rendercv_output/${file%_CV.yaml}"
          done
      - name: Upload rendercv_output as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: RenderCV Output
          path: rendercv_output
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          base: HEAD
          filters: |
            cv:
              - '*_CV.tex'
              - 'README.md'
      - name: Push the changes
        if: steps.changes.outputs.cv == 'true'
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git add -A
          git commit -m "render the latest CV"
          git push